version: '3'
services:
  keycloak:
    image: jboss/keycloak:10.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    expose:
      - 8080
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/tasks-realm.json"
    ports:
      - "8080:8080"
    volumes:
      - ./tasks-realm.json:/opt/jboss/keycloak/tasks-realm.json